// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq7H5hIowWvcGmIq7m2RofB843-Eyfz1g',
    appId: '1:861858508386:web:22dd1fc78ba3466b692b3b',
    messagingSenderId: '861858508386',
    projectId: 'cordrila',
    authDomain: 'cordrila.firebaseapp.com',
    databaseURL: 'https://cordrila-default-rtdb.firebaseio.com',
    storageBucket: 'cordrila.appspot.com',
    measurementId: 'G-MZLZL86DP6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4tJRzflin1O6UMabgoXdhEzf4WhAkHCo',
    appId: '1:861858508386:android:12eaa2ff301ccdd8692b3b',
    messagingSenderId: '861858508386',
    projectId: 'cordrila',
    databaseURL: 'https://cordrila-default-rtdb.firebaseio.com',
    storageBucket: 'cordrila.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjQthrt9SEnKt3r37zQz8tM0_LHfxrkyM',
    appId: '1:861858508386:ios:9adf14920cfd024e692b3b',
    messagingSenderId: '861858508386',
    projectId: 'cordrila',
    databaseURL: 'https://cordrila-default-rtdb.firebaseio.com',
    storageBucket: 'cordrila.appspot.com',
    iosBundleId: 'com.example.newApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjQthrt9SEnKt3r37zQz8tM0_LHfxrkyM',
    appId: '1:861858508386:ios:9adf14920cfd024e692b3b',
    messagingSenderId: '861858508386',
    projectId: 'cordrila',
    databaseURL: 'https://cordrila-default-rtdb.firebaseio.com',
    storageBucket: 'cordrila.appspot.com',
    iosBundleId: 'com.example.newApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDq7H5hIowWvcGmIq7m2RofB843-Eyfz1g',
    appId: '1:861858508386:web:9e018c02c4332589692b3b',
    messagingSenderId: '861858508386',
    projectId: 'cordrila',
    authDomain: 'cordrila.firebaseapp.com',
    databaseURL: 'https://cordrila-default-rtdb.firebaseio.com',
    storageBucket: 'cordrila.appspot.com',
    measurementId: 'G-K58Y830JFR',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDq7H5hIowWvcGmIq7m2RofB843-Eyfz1g',
    appId: '1:861858508386:web:c20f80d2f3a703b6692b3b',
    messagingSenderId: '861858508386',
    projectId: 'cordrila',
    authDomain: 'cordrila.firebaseapp.com',
    databaseURL: 'https://cordrila-default-rtdb.firebaseio.com',
    storageBucket: 'cordrila.appspot.com',
    measurementId: 'G-E3S2SW5SPY',
  );

}